// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbcuyuppurgzgqtdcaki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iY3V5dXBwdXJnemdxdGRjYWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Mzg1MjUsImV4cCI6MjA3MDUxNDUyNX0.x5rMpBLKZuITUiswi0napNHXyX7U6wlRGptUmq2oZTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});